# Generated by Django 5.2.9 on 2026-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans",
            "0007_rename_credit_investigation_at_loanapplication_second_approval_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
