# Generated by Django 5.2.9 on 2026-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_motor_chassis_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motor",
            old_name="chassis_number",
            new_name="plate_number",
        ),
        migrations.AlterField(
            model_name="motor",
            name="plate_number",
            field=models.CharField(
                blank=True, help_text="License Plate Number", max_length=100
            ),
        ),
    ]
