# Generated by Django 5.2.9 on 2026-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_rename_chassis_to_plate_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="motor",
            old_name="plate_number",
            new_name="chassis_plate_number",
        ),
        migrations.AlterField(
            model_name="motor",
            name="chassis_plate_number",
            field=models.CharField(
                blank=True,
                help_text="Chassis number or license plate number for unit identification",
                max_length=100,
                verbose_name="Chassis Number / Plate Number",
            ),
        ),
    ]
