# Generated by Django 5.2.9 on 2026-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("finance", "Finance")],
                default="admin",
                help_text="Primary access role determining permissions across modules.",
                max_length=20,
            ),
        ),
    ]
